name: Build & Test PR
on:
  pull_request_target:
    types: [opened, synchronize, edited]
concurrency: ci-${{ github.event.pull_request.head.ref}}
jobs:
  build-and-test:
    uses: ./.github/workflows/build-test-common.yml
    with:
      actor: ${{ github.actor }}
      ref: ${{ github.event.pull_request.head.ref }}
      commit: ${{ github.event.pull_request.head.sha }}
      is_main_branch: false
  auto-approve:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ github.actor == 'dependabot[bot]' }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: approve-dependabot
        if: github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        run: |
          gh pr review --approve || true
          gh pr merge --auto --rebase || true
  label:
    name: label when approved
    needs: auto-approve
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
    - name: label approved
      uses: abinoda/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        ADD_LABEL: "approved"
