# https://github.com/dependabot/dependabot-core/issues/1736
name: Update Lockfile Post Dependabot
on: pull_request_target
permissions: read-all
jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ^7
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GH_PA_TOKEN }}
    - run: pnpm i --lockfile-only
    - run: |
        git config --global user.name bbeesley-bot[bot]
        git config --global user.email bbeesley-bot[bot]@users.noreply.github.com
        git add pnpm-lock.yaml
        git commit -m "chore(deps): update pnpm-lock.yaml"
        git push
